remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Giggle"
description: "This app will give a joke pertaining to the word you put in."
author:
  name: "Layla"

# Do not change the following line.
  copyright: true
